#!/usr/bin/env bash
set -euo pipefail

out="$HOME/.openclaw/private/model-by-channel.json5"
telegram_id="${OPENCLAW_TELEGRAM_OWNER_ID:-}"

if [[ -z "$telegram_id" ]]; then
  content='// Generated by mise. Do not edit manually.
{"telegram": {}}'
else
  if [[ ! "$telegram_id" =~ ^[0-9]+$ ]]; then
    echo "OPENCLAW_TELEGRAM_OWNER_ID must be numeric" >&2
    exit 1
  fi

  content="// Generated by mise. Do not edit manually.
{\"telegram\":{\"$telegram_id\":\"gpt-5.5\"}}"
fi

mkdir -p "${out%/*}"

if [[ -f "$out" ]] && [[ "$(<"$out")" == "$content" ]]; then
  exit 0
fi

umask 077
printf '%s\n' "$content" > "$out"
chmod 600 "$out"
