#!/usr/bin/env bash

system_type=$(uname -s)

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi

if [ "$system_type" = "Darwin" ]; then

  git clone --depth=1 https://github.com/superbrothers/zsh-kubectl-prompt.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-kubectl-prompt
  git clone --depth=1 https://github.com/zsh-users/zsh-apple-touchbar.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-apple-touchbar

elif [[ "$system_type" = "WSL" ]] || [[ "$system_type" = "Linux" ]]; then


  sudo apt-get update
  sudo apt-get install build-essential

  echo "Install fonts from here: https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k"

  pause

else

  echo 'Unsupported OS'
  exit 1

fi

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

asdf install
helm plugin install https://github.com/databus23/helm-diff

# install krew
# https://krew.sigs.k8s.io/docs/user-guide/setup/install/
(
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
)
