#!/usr/bin/env bash

[[ hash brew &> /dev/null ]] || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install yadm # Install `yadm` following https://yadm.io/docs/install instructions otherwise

yadm clone https://github.com/kvokka/dotfiles
yadm bootstrap
yadm decrypt
