#!/usr/bin/env bash

hash brew &> /dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

brew install --force yadm # Install `yadm` following https://yadm.io/docs/install instructions otherwise

if [ -f "$HOME/./zshrc" ]; then
  echo "Existed .zshrc file found. Its recommended to remove it to allow YADM to do its job"
  rm -i ./zshrc
fi

yadm pull || yadm clone https://github.com/kvokka/dotfiles.git
yadm bootstrap
[ -f ~/.local/share/yadm/archive ] && yadm decrypt

# This hack allows us to use ssh for R/W access only in the case if we decided to decrypt the secrets
[ -f ~/.ssh/id_rsa ] && yadm remote set-url origin git@github.com:kvokka/dotfiles.git
