#!/usr/bin/env bash

hash brew &> /dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

brew install --force yadm # Install `yadm` following https://yadm.io/docs/install instructions otherwise

yadm pull || yadm clone https://github.com/kvokka/dotfiles.git
yadm bootstrap
yadm decrypt
