# ~/.zsh/alias_devc.zsh
unalias devc 2>/dev/null

# devc - Connect to a Docker container using an acronym or partial name
#
# Description:
#   Connects to a running Docker container by executing an interactive shell session.
#   Matches containers by:
#   - Acronym: Generated by taking the first letter of each word (up to three) before the numeric suffix (e.g., 'sa-web-app-1' -> 'sa-web-app' -> 'saa').
#   - Partial name: Case-insensitive substring match (e.g., 'web' matches 'sa-web-app-1').
#   If no input is provided and exactly one container is running, connects to it.
#   Fails with an error if multiple containers match or no match is found.
#
# Usage:
#   devc              # Connect to the only running container
#   devc <acronym>    # Connect to a container by its acronym (e.g., 'devc saa' for 'sa-web-app-1')
#   devc <partial>    # Connect to a container by partial name (e.g., 'devc web' for 'sa-web-app-1')
#
# Examples:
#   devc              # Connects to the only container if exactly one is running
#   devc saa          # Connects to 'sa-web-app-1' (acronym: 'saa')
#   devc web          # Connects to 'sa-web-app-1' (partial match: 'web')
#   devc bsa          # Connects to 'bank-support-agent-app-1' (acronym: 'bsa')
#   devc bank         # Connects to 'bank-support-agent-app-1' (partial match: 'bank')
#
# Environment Variables:
#   DEBUG             # Set to any value (e.g., '1') to enable debug output showing container names and acronyms
#
# Requirements:
#   - Docker CLI must be installed.
#   - Docker socket (/var/run/docker.sock) must be mounted in the container (via devcontainer.json).
#
# Notes:
#   - Fails with a list of running containers if multiple containers are running and no input is provided.
#   - Fails with an error if the input matches multiple containers ambiguously.
#   - Acronyms are generated by taking the first letter of up to three words before the numeric suffix.
#   - Tries to use zsh, falls back to bash, then sh if zsh is unavailable in the container.

# Helper function to determine available shell
get_available_shell() {
  local container_id="$1"
  local shell=""
  # Check for zsh
  if docker exec "$container_id" sh -c "[ -x /usr/bin/zsh ]" 2>/dev/null; then
    shell="/usr/bin/zsh"
  # Fallback to bash
  elif docker exec "$container_id" sh -c "[ -x /usr/bin/bash ]" 2>/dev/null; then
    shell="/usr/bin/bash"
  # Fallback to sh
  elif docker exec "$container_id" sh -c "[ -x /bin/sh ]" 2>/dev/null; then
    shell="/bin/sh"
  fi
  echo "$shell"
}

devc() {
  local input="$1"
  local container_id
  local container_name
  local matches
  local acronym

  # Get all running container names and IDs
  local containers
  containers=$(docker ps --format "{{.ID}} {{.Names}}" 2>/dev/null)
  if [[ -z "$containers" ]]; then
    echo "Error: No running Docker containers found."
    return 1
  fi

  # If no input provided, check if exactly one container is running
  if [[ -z "$input" ]]; then
    local count=$(echo "$containers" | wc -l)
    if [[ $count -eq 1 ]]; then
      container_id=$(echo "$containers" | awk '{print $1}')
      container_name=$(echo "$containers" | awk '{print $2}')
      echo "Connecting to the only running container: $container_name"
      local shell=$(get_available_shell "$container_id")
      if [[ -z "$shell" ]]; then
        echo "Error: No supported shell (zsh, bash, sh) found in container '$container_name'."
        return 1
      fi
      echo "Using shell: $shell"
      docker exec -it -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 "$container_id" "$shell"
      return $?
    else
      echo "Error: Multiple containers running. Specify an acronym or partial name."
      echo "Running containers:"
      echo "$containers" | awk '{print "  " $2}'
      return 1
    fi
  fi

  # Process input: match by acronym or partial name
  matches=()
  while read -r id name; do
    # Generate acronym: remove numeric suffix, take first letter of up to 3 words, lowercase
    acronym=$(echo "$name" | sed -E 's/-[0-9]+$//' | awk -F'[-_]' '{for(i=1; i<=NF && i<=3; i++) if ($i != "") {printf "%s", substr($i,1,1)}}' | tr '[:upper:]' '[:lower:]')
    # Debug: print container name and its acronym if DEBUG is set
    [[ -n "$DEBUG" ]] && echo "Debug: Container '$name' -> Acronym '$acronym'" >&2
    # Check for exact acronym match or partial name match (case-insensitive)
    local name_lower=$(echo "$name" | tr '[:upper:]' '[:lower:]')
    local input_lower=$(echo "$input" | tr '[:upper:]' '[:lower:]')
    if [[ "$acronym" == "$input" || "$name_lower" == *"$input_lower"* ]]; then
      matches+=("$id $name")
    fi
  done <<< "$containers"

  # Handle matches
  local match_count=${#matches[@]}
  if [[ $match_count -eq 0 ]]; then
    echo "Error: No containers match '$input'."
    echo "Running containers:"
    echo "$containers" | awk '{print "  " $2}'
    return 1
  elif [[ $match_count -eq 1 ]]; then
    container_id=${matches[1]%% *}
    container_name=${matches[1]#* }
    echo "Connecting to container: $container_name"
    if [[ -z "$container_id" ]]; then
      echo "Error: Invalid container ID for '$container_name'."
      return 1
    fi
    local shell=$(get_available_shell "$container_id")
    if [[ -z "$shell" ]]; then
      echo "Error: No supported shell (zsh, bash, sh) found in container '$container_name'."
      return 1
    fi
    echo "Using shell: $shell"
    docker exec -it -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 "$container_id" "$shell"
    return $?
  else
    echo "Error: Multiple containers match '$input':"
    for match in "${matches[@]}"; do
      echo "  $match"
    done
    echo "Please use a more specific acronym or partial name."
    return 1
  fi
}
