zshPlugins:
  - "mise"
  - "cp"
  - "docker"
  - "direnv"
  - "gcloud"
  - "git"
  - "github"
  - "golang"
  - "kubectl"
  - "npm"
  - "sudo"
  - "uv"
  - "zsh-navigation-tools"
  - "helm"
  - "zsh-autosuggestions"
  - "zsh-syntax-highlighting"
  - "bun"
  - "gh"
  - "ssh"
  - "terraform"
  - "zoxide"
  - "ssh-agent"

my_cli_llm_proxy:
  host: "https://p01--cpa--vyz4vtzxq2zw.code.run"
  url:  "https://p01--cpa--vyz4vtzxq2zw.code.run/v1"
