(( $+commands[atuin] )) || return
# shells spawned by coding agents must not pollute the shell history
[[ -n "${CLAUDECODE:-}${CLAUDE_PROJECT_DIR:-}${CODEX_THREAD_ID:-}${CODEX_CI:-}${AGENT_NAME:-}" ]] && return
# completions are generated by `mise run bootstrap:atuin`; self-heal if missing
[[ -f "${0:h}/_atuin" ]] || atuin gen-completions --shell zsh --out-dir "${0:h}" >/dev/null 2>&1
eval "$(atuin init zsh --disable-up-arrow)"
